// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway-server/pkg/proto/auth.proto

package serverProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	RefreshToken         string   `protobuf:"bytes,6,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	PeopleNumber         int64    `protobuf:"varint,7,opt,name=peopleNumber,proto3" json:"peopleNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *User) GetPeopleNumber() int64 {
	if m != nil {
		return m.PeopleNumber
	}
	return 0
}

type Developer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	PrimarySkill         string   `protobuf:"bytes,4,opt,name=primarySkill,proto3" json:"primarySkill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Developer) Reset()         { *m = Developer{} }
func (m *Developer) String() string { return proto.CompactTextString(m) }
func (*Developer) ProtoMessage()    {}
func (*Developer) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{1}
}
func (m *Developer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Developer.Unmarshal(m, b)
}
func (m *Developer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Developer.Marshal(b, m, deterministic)
}
func (dst *Developer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Developer.Merge(dst, src)
}
func (m *Developer) XXX_Size() int {
	return xxx_messageInfo_Developer.Size(m)
}
func (m *Developer) XXX_DiscardUnknown() {
	xxx_messageInfo_Developer.DiscardUnknown(m)
}

var xxx_messageInfo_Developer proto.InternalMessageInfo

func (m *Developer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Developer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Developer) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Developer) GetPrimarySkill() string {
	if m != nil {
		return m.PrimarySkill
	}
	return ""
}

type CreateDeveloperRequest struct {
	Developer            *Developer `protobuf:"bytes,1,opt,name=developer,proto3" json:"developer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateDeveloperRequest) Reset()         { *m = CreateDeveloperRequest{} }
func (m *CreateDeveloperRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeveloperRequest) ProtoMessage()    {}
func (*CreateDeveloperRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{2}
}
func (m *CreateDeveloperRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeveloperRequest.Unmarshal(m, b)
}
func (m *CreateDeveloperRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeveloperRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDeveloperRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeveloperRequest.Merge(dst, src)
}
func (m *CreateDeveloperRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeveloperRequest.Size(m)
}
func (m *CreateDeveloperRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeveloperRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeveloperRequest proto.InternalMessageInfo

func (m *CreateDeveloperRequest) GetDeveloper() *Developer {
	if m != nil {
		return m.Developer
	}
	return nil
}

type CreateDeveloperResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeveloperResponse) Reset()         { *m = CreateDeveloperResponse{} }
func (m *CreateDeveloperResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeveloperResponse) ProtoMessage()    {}
func (*CreateDeveloperResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{3}
}
func (m *CreateDeveloperResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeveloperResponse.Unmarshal(m, b)
}
func (m *CreateDeveloperResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeveloperResponse.Marshal(b, m, deterministic)
}
func (dst *CreateDeveloperResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeveloperResponse.Merge(dst, src)
}
func (m *CreateDeveloperResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeveloperResponse.Size(m)
}
func (m *CreateDeveloperResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeveloperResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeveloperResponse proto.InternalMessageInfo

func (m *CreateDeveloperResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadDeveloperRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadDeveloperRequest) Reset()         { *m = ReadDeveloperRequest{} }
func (m *ReadDeveloperRequest) String() string { return proto.CompactTextString(m) }
func (*ReadDeveloperRequest) ProtoMessage()    {}
func (*ReadDeveloperRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{4}
}
func (m *ReadDeveloperRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadDeveloperRequest.Unmarshal(m, b)
}
func (m *ReadDeveloperRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadDeveloperRequest.Marshal(b, m, deterministic)
}
func (dst *ReadDeveloperRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadDeveloperRequest.Merge(dst, src)
}
func (m *ReadDeveloperRequest) XXX_Size() int {
	return xxx_messageInfo_ReadDeveloperRequest.Size(m)
}
func (m *ReadDeveloperRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadDeveloperRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadDeveloperRequest proto.InternalMessageInfo

func (m *ReadDeveloperRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadDeveloperResponse struct {
	Developer            *Developer `protobuf:"bytes,1,opt,name=developer,proto3" json:"developer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadDeveloperResponse) Reset()         { *m = ReadDeveloperResponse{} }
func (m *ReadDeveloperResponse) String() string { return proto.CompactTextString(m) }
func (*ReadDeveloperResponse) ProtoMessage()    {}
func (*ReadDeveloperResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{5}
}
func (m *ReadDeveloperResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadDeveloperResponse.Unmarshal(m, b)
}
func (m *ReadDeveloperResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadDeveloperResponse.Marshal(b, m, deterministic)
}
func (dst *ReadDeveloperResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadDeveloperResponse.Merge(dst, src)
}
func (m *ReadDeveloperResponse) XXX_Size() int {
	return xxx_messageInfo_ReadDeveloperResponse.Size(m)
}
func (m *ReadDeveloperResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadDeveloperResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadDeveloperResponse proto.InternalMessageInfo

func (m *ReadDeveloperResponse) GetDeveloper() *Developer {
	if m != nil {
		return m.Developer
	}
	return nil
}

type UpdateDeveloperRequest struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Developer            *Developer `protobuf:"bytes,2,opt,name=developer,proto3" json:"developer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateDeveloperRequest) Reset()         { *m = UpdateDeveloperRequest{} }
func (m *UpdateDeveloperRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDeveloperRequest) ProtoMessage()    {}
func (*UpdateDeveloperRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{6}
}
func (m *UpdateDeveloperRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeveloperRequest.Unmarshal(m, b)
}
func (m *UpdateDeveloperRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeveloperRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateDeveloperRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeveloperRequest.Merge(dst, src)
}
func (m *UpdateDeveloperRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDeveloperRequest.Size(m)
}
func (m *UpdateDeveloperRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeveloperRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeveloperRequest proto.InternalMessageInfo

func (m *UpdateDeveloperRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateDeveloperRequest) GetDeveloper() *Developer {
	if m != nil {
		return m.Developer
	}
	return nil
}

type UpdateDeveloperResponse struct {
	Developer            *Developer `protobuf:"bytes,1,opt,name=developer,proto3" json:"developer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateDeveloperResponse) Reset()         { *m = UpdateDeveloperResponse{} }
func (m *UpdateDeveloperResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDeveloperResponse) ProtoMessage()    {}
func (*UpdateDeveloperResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{7}
}
func (m *UpdateDeveloperResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeveloperResponse.Unmarshal(m, b)
}
func (m *UpdateDeveloperResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeveloperResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateDeveloperResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeveloperResponse.Merge(dst, src)
}
func (m *UpdateDeveloperResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDeveloperResponse.Size(m)
}
func (m *UpdateDeveloperResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeveloperResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeveloperResponse proto.InternalMessageInfo

func (m *UpdateDeveloperResponse) GetDeveloper() *Developer {
	if m != nil {
		return m.Developer
	}
	return nil
}

type DeleteDeveloperRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeveloperRequest) Reset()         { *m = DeleteDeveloperRequest{} }
func (m *DeleteDeveloperRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeveloperRequest) ProtoMessage()    {}
func (*DeleteDeveloperRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{8}
}
func (m *DeleteDeveloperRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeveloperRequest.Unmarshal(m, b)
}
func (m *DeleteDeveloperRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeveloperRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteDeveloperRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeveloperRequest.Merge(dst, src)
}
func (m *DeleteDeveloperRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeveloperRequest.Size(m)
}
func (m *DeleteDeveloperRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeveloperRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeveloperRequest proto.InternalMessageInfo

func (m *DeleteDeveloperRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteDeveloperResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeveloperResponse) Reset()         { *m = DeleteDeveloperResponse{} }
func (m *DeleteDeveloperResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDeveloperResponse) ProtoMessage()    {}
func (*DeleteDeveloperResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{9}
}
func (m *DeleteDeveloperResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeveloperResponse.Unmarshal(m, b)
}
func (m *DeleteDeveloperResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeveloperResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteDeveloperResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeveloperResponse.Merge(dst, src)
}
func (m *DeleteDeveloperResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDeveloperResponse.Size(m)
}
func (m *DeleteDeveloperResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeveloperResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeveloperResponse proto.InternalMessageInfo

type ReadAllDevelopersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllDevelopersRequest) Reset()         { *m = ReadAllDevelopersRequest{} }
func (m *ReadAllDevelopersRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAllDevelopersRequest) ProtoMessage()    {}
func (*ReadAllDevelopersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{10}
}
func (m *ReadAllDevelopersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllDevelopersRequest.Unmarshal(m, b)
}
func (m *ReadAllDevelopersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllDevelopersRequest.Marshal(b, m, deterministic)
}
func (dst *ReadAllDevelopersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllDevelopersRequest.Merge(dst, src)
}
func (m *ReadAllDevelopersRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAllDevelopersRequest.Size(m)
}
func (m *ReadAllDevelopersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllDevelopersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllDevelopersRequest proto.InternalMessageInfo

type ReadAllDevelopersResponse struct {
	Developers           []*Developer `protobuf:"bytes,1,rep,name=developers,proto3" json:"developers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReadAllDevelopersResponse) Reset()         { *m = ReadAllDevelopersResponse{} }
func (m *ReadAllDevelopersResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllDevelopersResponse) ProtoMessage()    {}
func (*ReadAllDevelopersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{11}
}
func (m *ReadAllDevelopersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllDevelopersResponse.Unmarshal(m, b)
}
func (m *ReadAllDevelopersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllDevelopersResponse.Marshal(b, m, deterministic)
}
func (dst *ReadAllDevelopersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllDevelopersResponse.Merge(dst, src)
}
func (m *ReadAllDevelopersResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllDevelopersResponse.Size(m)
}
func (m *ReadAllDevelopersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllDevelopersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllDevelopersResponse proto.InternalMessageInfo

func (m *ReadAllDevelopersResponse) GetDevelopers() []*Developer {
	if m != nil {
		return m.Developers
	}
	return nil
}

type SignInRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{12}
}
func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (dst *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(dst, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{13}
}
func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (dst *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(dst, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *SignInResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type SignUpRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{14}
}
func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (dst *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(dst, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignUpResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e18d5244711d097c, []int{15}
}
func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (dst *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(dst, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *SignUpResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "serverProto.User")
	proto.RegisterType((*Developer)(nil), "serverProto.Developer")
	proto.RegisterType((*CreateDeveloperRequest)(nil), "serverProto.CreateDeveloperRequest")
	proto.RegisterType((*CreateDeveloperResponse)(nil), "serverProto.CreateDeveloperResponse")
	proto.RegisterType((*ReadDeveloperRequest)(nil), "serverProto.ReadDeveloperRequest")
	proto.RegisterType((*ReadDeveloperResponse)(nil), "serverProto.ReadDeveloperResponse")
	proto.RegisterType((*UpdateDeveloperRequest)(nil), "serverProto.UpdateDeveloperRequest")
	proto.RegisterType((*UpdateDeveloperResponse)(nil), "serverProto.UpdateDeveloperResponse")
	proto.RegisterType((*DeleteDeveloperRequest)(nil), "serverProto.DeleteDeveloperRequest")
	proto.RegisterType((*DeleteDeveloperResponse)(nil), "serverProto.DeleteDeveloperResponse")
	proto.RegisterType((*ReadAllDevelopersRequest)(nil), "serverProto.ReadAllDevelopersRequest")
	proto.RegisterType((*ReadAllDevelopersResponse)(nil), "serverProto.ReadAllDevelopersResponse")
	proto.RegisterType((*SignInRequest)(nil), "serverProto.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "serverProto.SignInResponse")
	proto.RegisterType((*SignUpRequest)(nil), "serverProto.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "serverProto.SignUpResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RestAppClient is the client API for RestApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestAppClient interface {
	ReadAllDevelopers(ctx context.Context, in *ReadAllDevelopersRequest, opts ...grpc.CallOption) (*ReadAllDevelopersResponse, error)
	CreateDeveloper(ctx context.Context, in *CreateDeveloperRequest, opts ...grpc.CallOption) (*CreateDeveloperResponse, error)
	ReadDeveloper(ctx context.Context, in *ReadDeveloperRequest, opts ...grpc.CallOption) (*ReadDeveloperResponse, error)
	UpdateDeveloper(ctx context.Context, in *UpdateDeveloperRequest, opts ...grpc.CallOption) (*UpdateDeveloperResponse, error)
	DeleteDeveloper(ctx context.Context, in *DeleteDeveloperRequest, opts ...grpc.CallOption) (*DeleteDeveloperResponse, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
}

type restAppClient struct {
	cc *grpc.ClientConn
}

func NewRestAppClient(cc *grpc.ClientConn) RestAppClient {
	return &restAppClient{cc}
}

func (c *restAppClient) ReadAllDevelopers(ctx context.Context, in *ReadAllDevelopersRequest, opts ...grpc.CallOption) (*ReadAllDevelopersResponse, error) {
	out := new(ReadAllDevelopersResponse)
	err := c.cc.Invoke(ctx, "/serverProto.RestApp/ReadAllDevelopers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restAppClient) CreateDeveloper(ctx context.Context, in *CreateDeveloperRequest, opts ...grpc.CallOption) (*CreateDeveloperResponse, error) {
	out := new(CreateDeveloperResponse)
	err := c.cc.Invoke(ctx, "/serverProto.RestApp/CreateDeveloper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restAppClient) ReadDeveloper(ctx context.Context, in *ReadDeveloperRequest, opts ...grpc.CallOption) (*ReadDeveloperResponse, error) {
	out := new(ReadDeveloperResponse)
	err := c.cc.Invoke(ctx, "/serverProto.RestApp/ReadDeveloper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restAppClient) UpdateDeveloper(ctx context.Context, in *UpdateDeveloperRequest, opts ...grpc.CallOption) (*UpdateDeveloperResponse, error) {
	out := new(UpdateDeveloperResponse)
	err := c.cc.Invoke(ctx, "/serverProto.RestApp/UpdateDeveloper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restAppClient) DeleteDeveloper(ctx context.Context, in *DeleteDeveloperRequest, opts ...grpc.CallOption) (*DeleteDeveloperResponse, error) {
	out := new(DeleteDeveloperResponse)
	err := c.cc.Invoke(ctx, "/serverProto.RestApp/DeleteDeveloper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restAppClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/serverProto.RestApp/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restAppClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/serverProto.RestApp/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestAppServer is the server API for RestApp service.
type RestAppServer interface {
	ReadAllDevelopers(context.Context, *ReadAllDevelopersRequest) (*ReadAllDevelopersResponse, error)
	CreateDeveloper(context.Context, *CreateDeveloperRequest) (*CreateDeveloperResponse, error)
	ReadDeveloper(context.Context, *ReadDeveloperRequest) (*ReadDeveloperResponse, error)
	UpdateDeveloper(context.Context, *UpdateDeveloperRequest) (*UpdateDeveloperResponse, error)
	DeleteDeveloper(context.Context, *DeleteDeveloperRequest) (*DeleteDeveloperResponse, error)
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
}

func RegisterRestAppServer(s *grpc.Server, srv RestAppServer) {
	s.RegisterService(&_RestApp_serviceDesc, srv)
}

func _RestApp_ReadAllDevelopers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllDevelopersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestAppServer).ReadAllDevelopers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverProto.RestApp/ReadAllDevelopers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestAppServer).ReadAllDevelopers(ctx, req.(*ReadAllDevelopersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestApp_CreateDeveloper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeveloperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestAppServer).CreateDeveloper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverProto.RestApp/CreateDeveloper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestAppServer).CreateDeveloper(ctx, req.(*CreateDeveloperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestApp_ReadDeveloper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDeveloperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestAppServer).ReadDeveloper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverProto.RestApp/ReadDeveloper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestAppServer).ReadDeveloper(ctx, req.(*ReadDeveloperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestApp_UpdateDeveloper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeveloperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestAppServer).UpdateDeveloper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverProto.RestApp/UpdateDeveloper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestAppServer).UpdateDeveloper(ctx, req.(*UpdateDeveloperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestApp_DeleteDeveloper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeveloperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestAppServer).DeleteDeveloper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverProto.RestApp/DeleteDeveloper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestAppServer).DeleteDeveloper(ctx, req.(*DeleteDeveloperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestApp_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestAppServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverProto.RestApp/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestAppServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestApp_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestAppServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverProto.RestApp/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestAppServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RestApp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverProto.RestApp",
	HandlerType: (*RestAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAllDevelopers",
			Handler:    _RestApp_ReadAllDevelopers_Handler,
		},
		{
			MethodName: "CreateDeveloper",
			Handler:    _RestApp_CreateDeveloper_Handler,
		},
		{
			MethodName: "ReadDeveloper",
			Handler:    _RestApp_ReadDeveloper_Handler,
		},
		{
			MethodName: "UpdateDeveloper",
			Handler:    _RestApp_UpdateDeveloper_Handler,
		},
		{
			MethodName: "DeleteDeveloper",
			Handler:    _RestApp_DeleteDeveloper_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _RestApp_SignIn_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _RestApp_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway-server/pkg/proto/auth.proto",
}

func init() {
	proto.RegisterFile("gateway-server/pkg/proto/auth.proto", fileDescriptor_auth_e18d5244711d097c)
}

var fileDescriptor_auth_e18d5244711d097c = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xdf, 0x4e, 0x13, 0x4f,
	0x14, 0xc7, 0xb3, 0x6d, 0x29, 0x3f, 0x0e, 0x3f, 0x40, 0x46, 0x6c, 0xb7, 0x2b, 0xc6, 0x32, 0x08,
	0x01, 0x12, 0xd9, 0x88, 0x86, 0x0b, 0xee, 0x88, 0xdc, 0x78, 0x21, 0x9a, 0xc5, 0x7a, 0x65, 0x4c,
	0x06, 0xf6, 0xb8, 0x6c, 0xd8, 0xee, 0x8c, 0x3b, 0x5b, 0x08, 0x69, 0x6a, 0x8c, 0xaf, 0xe0, 0xdb,
	0xf8, 0x0e, 0x5e, 0xf9, 0x0a, 0x3e, 0x88, 0xd9, 0xd9, 0x3f, 0xed, 0xfe, 0x29, 0x18, 0xf5, 0x6e,
	0xe6, 0x9c, 0xb3, 0xe7, 0xf3, 0x3d, 0x33, 0xfd, 0x4e, 0x61, 0xdd, 0x61, 0x21, 0x5e, 0xb1, 0xeb,
	0xc7, 0x12, 0x83, 0x4b, 0x0c, 0x4c, 0x71, 0xe1, 0x98, 0x22, 0xe0, 0x21, 0x37, 0xd9, 0x20, 0x3c,
	0xdf, 0x55, 0x4b, 0x32, 0x1f, 0x27, 0x5f, 0x47, 0x1b, 0x63, 0xd5, 0xe1, 0xdc, 0xf1, 0xd0, 0x64,
	0xc2, 0x35, 0x99, 0xef, 0xf3, 0x90, 0x85, 0x2e, 0xf7, 0x65, 0x5c, 0x4a, 0xbf, 0x69, 0xd0, 0xe8,
	0x49, 0x0c, 0xc8, 0x22, 0xd4, 0x5c, 0x5b, 0xd7, 0xba, 0xda, 0x56, 0xdd, 0xaa, 0xb9, 0x36, 0x59,
	0x81, 0x19, 0x8f, 0x3b, 0xae, 0xaf, 0xd7, 0xba, 0xda, 0xd6, 0x9c, 0x15, 0x6f, 0xa2, 0x28, 0xf6,
	0x99, 0xeb, 0xe9, 0xf5, 0x38, 0xaa, 0x36, 0xc4, 0x80, 0xff, 0x04, 0x93, 0xf2, 0x8a, 0x07, 0xb6,
	0xde, 0x50, 0x89, 0x6c, 0x4f, 0x08, 0x34, 0x02, 0xee, 0xa1, 0x3e, 0xa3, 0xe2, 0x6a, 0x4d, 0x28,
	0xfc, 0x1f, 0xe0, 0x87, 0x00, 0xe5, 0xf9, 0x1b, 0x7e, 0x81, 0xbe, 0xde, 0x54, 0xb9, 0x5c, 0x2c,
	0xaa, 0x11, 0xc8, 0x85, 0x87, 0xc7, 0x83, 0xfe, 0x29, 0x06, 0xfa, 0xac, 0x52, 0x96, 0x8b, 0x51,
	0x84, 0xb9, 0x23, 0xbc, 0x44, 0x8f, 0x8b, 0x8a, 0x01, 0x08, 0x34, 0x7c, 0xd6, 0xc7, 0x44, 0xbf,
	0x5a, 0x93, 0x3b, 0x50, 0x67, 0x0e, 0x2a, 0xf1, 0x75, 0x2b, 0x5a, 0x2a, 0x4c, 0xe0, 0xf6, 0x59,
	0x70, 0x7d, 0x72, 0xe1, 0x7a, 0x5e, 0x22, 0x3f, 0x17, 0xa3, 0xc7, 0xd0, 0x7a, 0x1e, 0x20, 0x0b,
	0x31, 0x83, 0x59, 0xf8, 0x71, 0x80, 0x32, 0x24, 0xcf, 0x60, 0xce, 0x4e, 0x63, 0x0a, 0x3d, 0xbf,
	0xd7, 0xda, 0x9d, 0x38, 0xfc, 0xdd, 0xf1, 0x17, 0xe3, 0x42, 0xba, 0x0d, 0xed, 0x52, 0x3f, 0x29,
	0xb8, 0x2f, 0xb1, 0x38, 0x04, 0xdd, 0x84, 0x15, 0x0b, 0x99, 0x5d, 0x02, 0x17, 0xeb, 0x5e, 0xc2,
	0xbd, 0x42, 0x5d, 0xd2, 0xf0, 0xcf, 0x14, 0xbe, 0x87, 0x56, 0x4f, 0xd8, 0x55, 0x13, 0x17, 0x4f,
	0x39, 0xd7, 0xbf, 0xf6, 0xbb, 0xfd, 0x5f, 0x41, 0xbb, 0xd4, 0xff, 0xaf, 0x04, 0x6f, 0x41, 0xeb,
	0x08, 0x3d, 0xbc, 0x5d, 0x30, 0xed, 0x40, 0xbb, 0x54, 0x19, 0xa3, 0xa9, 0x01, 0x7a, 0x74, 0x88,
	0x87, 0x9e, 0x97, 0xe5, 0x64, 0xd2, 0x86, 0x9e, 0x40, 0xa7, 0x22, 0x97, 0x68, 0xde, 0x07, 0xc8,
	0xa4, 0x48, 0x5d, 0xeb, 0xd6, 0x6f, 0x10, 0x3d, 0x51, 0x49, 0x0f, 0x61, 0xe1, 0xc4, 0x75, 0xfc,
	0x17, 0x7e, 0x2a, 0x36, 0x33, 0x9d, 0x36, 0x69, 0xba, 0x49, 0x7b, 0xd5, 0xf2, 0xf6, 0xa2, 0x6f,
	0x61, 0x31, 0x6d, 0x91, 0x88, 0xe9, 0xc2, 0x3c, 0x3b, 0x3b, 0x43, 0x29, 0x63, 0x6f, 0xc5, 0x9d,
	0x26, 0x43, 0x25, 0xfb, 0xd5, 0xca, 0xf6, 0xa3, 0xfb, 0xb1, 0xb4, 0x9e, 0x48, 0xa5, 0x6d, 0x40,
	0x63, 0x20, 0xb3, 0x2b, 0x59, 0xce, 0x4d, 0x17, 0x3d, 0x20, 0x96, 0x4a, 0xa7, 0x7a, 0xa2, 0xef,
	0xfe, 0xa5, 0x9e, 0xbd, 0xef, 0x4d, 0x98, 0xb5, 0x50, 0x86, 0x87, 0x42, 0x90, 0x4f, 0xb0, 0x5c,
	0xba, 0x0b, 0xb2, 0x91, 0x53, 0x34, 0xed, 0x1e, 0x8d, 0xcd, 0xdb, 0xca, 0xd2, 0xdf, 0xc2, 0x97,
	0x1f, 0x3f, 0xbf, 0xd6, 0x56, 0x08, 0x51, 0xef, 0xe6, 0xe5, 0x13, 0x73, 0x7c, 0x6d, 0x64, 0x08,
	0x4b, 0x05, 0xff, 0x92, 0xf5, 0x5c, 0xdb, 0xea, 0xd7, 0xc2, 0x78, 0x74, 0x73, 0x51, 0x42, 0x7e,
	0xa0, 0xc8, 0x6d, 0x5a, 0x41, 0x3e, 0xd0, 0x76, 0xc8, 0x15, 0x2c, 0xe4, 0x9c, 0x4e, 0xd6, 0x4a,
	0x13, 0x95, 0xc0, 0xf4, 0xa6, 0x92, 0x04, 0xfb, 0x50, 0x61, 0x3b, 0xa4, 0x5d, 0xc6, 0x9a, 0x43,
	0xd7, 0x1e, 0x91, 0xcf, 0x1a, 0x2c, 0x15, 0x4c, 0x5b, 0x18, 0xbb, 0xfa, 0xc9, 0x28, 0x8c, 0x3d,
	0xc5, 0xf7, 0x94, 0x2a, 0xfe, 0xaa, 0x31, 0x8d, 0x1f, 0xcd, 0x3e, 0x82, 0xa5, 0x82, 0x77, 0x0b,
	0x0a, 0xaa, 0xdf, 0x80, 0x82, 0x82, 0x69, 0xf6, 0x4f, 0x4e, 0x60, 0x67, 0xea, 0x09, 0x78, 0xd0,
	0x8c, 0xbd, 0x46, 0x8c, 0x5c, 0xc3, 0x9c, 0x87, 0x8d, 0xfb, 0x95, 0xb9, 0x84, 0xb1, 0xad, 0x18,
	0xeb, 0x64, 0x2d, 0x65, 0x48, 0xd7, 0xf1, 0x5d, 0xdf, 0x1c, 0x2a, 0xa7, 0x8f, 0xcc, 0x61, 0x6a,
	0xec, 0x11, 0x79, 0x17, 0xd3, 0x7a, 0xa2, 0x82, 0x96, 0xd9, 0xb2, 0x82, 0x36, 0xb6, 0x1e, 0xed,
	0x28, 0xda, 0x5d, 0xba, 0x38, 0x49, 0x1b, 0x88, 0x03, 0x6d, 0xe7, 0xb4, 0xa9, 0xfe, 0xfe, 0x9f,
	0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xc4, 0xb9, 0x51, 0x50, 0x08, 0x00, 0x00,
}
